### PR TITLE
Fix#20 

### PR DESCRIPTION
**Pull request by NakanoMizuki**
Change error message at the shipping form

### CODE REVIEW

**Comment by nabedge** [comment]
We should create messages.properties file and use it.

See also https://github.com/nabedge/mixer2-sample/blob/master/mixer2-fruitshop-springboot/src/main/java/org/mixer2/sample/config/SpringConfig.java#L66

**Comment by NakanoMizuki** [comment]
I forked old master.
So, I rebase Fix#20.

**Comment by NakanoMizuki** [comment]
Get error message from src/main/resources/messages.properties

Output

**Comment by NakanoMizuki** [comment]
Thanks !

**Pull request merged**
